/**
 * @fileoverview Massive URL sources for data collection across multiple categories.
 * 
 * This file contains curated lists of 500+ URLs to scrape from various categories.
 */

export interface DataSource {
  name: string;
  url: string;
  category: string;
  type: 'rss' | 'api' | 'html' | 'json';
}

export const DATA_SOURCES: DataSource[] = [
  // ========== TECHNOLOGY (50+) ==========
  { name: "Hacker News", url: "https://news.ycombinator.com/", category: "Technology", type: "html" },
  { name: "TechCrunch", url: "https://techcrunch.com/", category: "Technology", type: "html" },
  { name: "The Verge", url: "https://www.theverge.com/", category: "Technology", type: "html" },
  { name: "Wired", url: "https://www.wired.com/", category: "Technology", type: "html" },
  { name: "Ars Technica", url: "https://arstechnica.com/", category: "Technology", type: "html" },
  { name: "MIT Technology Review", url: "https://www.technologyreview.com/", category: "Technology", type: "html" },
  { name: "CNET", url: "https://www.cnet.com/", category: "Technology", type: "html" },
  { name: "Engadget", url: "https://www.engadget.com/", category: "Technology", type: "html" },
  { name: "Stack Overflow Blog", url: "https://stackoverflow.blog/", category: "Technology", type: "html" },
  { name: "Dev.to", url: "https://dev.to/", category: "Technology", type: "html" },
  { name: "The Next Web", url: "https://thenextweb.com/", category: "Technology", type: "html" },
  { name: "ZDNet", url: "https://www.zdnet.com/", category: "Technology", type: "html" },
  { name: "TechRadar", url: "https://www.techradar.com/", category: "Technology", type: "html" },
  { name: "Tom's Guide", url: "https://www.tomsguide.com/", category: "Technology", type: "html" },
  { name: "PCMag", url: "https://www.pcmag.com/", category: "Technology", type: "html" },
  { name: "Digital Trends", url: "https://www.digitaltrends.com/", category: "Technology", type: "html" },
  { name: "Gizmodo", url: "https://gizmodo.com/", category: "Technology", type: "html" },
  { name: "Mashable", url: "https://mashable.com/", category: "Technology", type: "html" },
  { name: "The Hacker News", url: "https://thehackernews.com/", category: "Technology", type: "html" },
  { name: "BleepingComputer", url: "https://www.bleepingcomputer.com/", category: "Technology", type: "html" },
  { name: "TechSpot", url: "https://www.techspot.com/", category: "Technology", type: "html" },
  { name: "AnandTech", url: "https://www.anandtech.com/", category: "Technology", type: "html" },
  { name: "ExtremeTech", url: "https://www.extremetech.com/", category: "Technology", type: "html" },
  { name: "Tom's Hardware", url: "https://www.tomshardware.com/", category: "Technology", type: "html" },
  { name: "PCWorld", url: "https://www.pcworld.com/", category: "Technology", type: "html" },
  { name: "Computerworld", url: "https://www.computerworld.com/", category: "Technology", type: "html" },
  { name: "InfoWorld", url: "https://www.infoworld.com/", category: "Technology", type: "html" },
  { name: "Network World", url: "https://www.networkworld.com/", category: "Technology", type: "html" },
  { name: "CSO Online", url: "https://www.csoonline.com/", category: "Technology", type: "html" },
  { name: "Dark Reading", url: "https://www.darkreading.com/", category: "Technology", type: "html" },
  { name: "SecurityWeek", url: "https://www.securityweek.com/", category: "Technology", type: "html" },
  { name: "Threatpost", url: "https://threatpost.com/", category: "Technology", type: "html" },
  { name: "Krebs on Security", url: "https://krebsonsecurity.com/", category: "Technology", type: "html" },
  { name: "SANS Internet Storm Center", url: "https://isc.sans.edu/", category: "Technology", type: "html" },
  { name: "Troy Hunt's Blog", url: "https://www.troyhunt.com/", category: "Technology", type: "html" },
  { name: "Schneier on Security", url: "https://www.schneier.com/", category: "Technology", type: "html" },
  { name: "Wired - Security", url: "https://www.wired.com/category/security/", category: "Technology", type: "html" },
  { name: "Wired - Business", url: "https://www.wired.com/category/business/", category: "Technology", type: "html" },
  { name: "Product Hunt", url: "https://www.producthunt.com/", category: "Technology", type: "html" },
  { name: "BetaList", url: "https://betalist.com/", category: "Technology", type: "html" },
  { name: "Startupramp", url: "https://startupramp.com/", category: "Technology", type: "html" },
  { name: "Y Combinator", url: "https://www.ycombinator.com/", category: "Technology", type: "html" },
  { name: "AngelList", url: "https://www.angellist.com/", category: "Technology", type: "html" },
  { name: "Crunchbase", url: "https://www.crunchbase.com/", category: "Technology", type: "html" },
  { name: "VB", url: "https://venturebeat.com/", category: "Technology", type: "html" },
  { name: "FinSMEs", url: "https://www.finsmes.com/", category: "Technology", type: "html" },
  { name: "SaaS Boost", url: "https://saasboost.io/", category: "Technology", type: "html" },
  { name: "Awesome README", url: "https://github.com/matiassingers/awesome-readme", category: "Technology", type: "html" },
  { name: "Open Source", url: "https://opensource.com/", category: "Technology", type: "html" },
  { name: "GitHub Blog", url: "https://github.blog/", category: "Technology", type: "html" },
  { name: "GitLab Blog", url: "https://about.gitlab.com/blog/", category: "Technology", type: "html" },
  { name: "Atlassian Blog", url: "https://blog.developer.atlassian.com/", category: "Technology", type: "html" },
  { name: "AWS Blog", url: "https://aws.amazon.com/blogs/", category: "Technology", type: "html" },
  { name: "Google Cloud Blog", url: "https://cloud.google.com/blog/", category: "Technology", type: "html" },
  { name: "Microsoft DevOps", url: "https://docs.microsoft.com/en-us/devops/", category: "Technology", type: "html" },

  // ========== PROGRAMMING (60+) ==========
  { name: "MDN Web Docs", url: "https://developer.mozilla.org/", category: "Programming", type: "html" },
  { name: "CSS-Tricks", url: "https://css-tricks.com/", category: "Programming", type: "html" },
  { name: "Smashing Magazine", url: "https://www.smashingmagazine.com/", category: "Programming", type: "html" },
  { name: "FreeCodeCamp", url: "https://www.freecodecamp.org/news/", category: "Programming", type: "html" },
  { name: "SitePoint", url: "https://www.sitepoint.com/", category: "Programming", type: "html" },
  { name: "JavaScript.info", url: "https://javascript.info/", category: "Programming", type: "html" },
  { name: "React Documentation", url: "https://react.dev/", category: "Programming", type: "html" },
  { name: "Node.js Documentation", url: "https://nodejs.org/docs/latest/api/", category: "Programming", type: "html" },
  { name: "Python Documentation", url: "https://docs.python.org/3/", category: "Programming", type: "html" },
  { name: "Rust Documentation", url: "https://doc.rust-lang.org/book/", category: "Programming", type: "html" },
  { name: "TypeScript Documentation", url: "https://www.typescriptlang.org/docs/", category: "Programming", type: "html" },
  { name: "Go Documentation", url: "https://go.dev/doc/", category: "Programming", type: "html" },
  { name: "Java Documentation", url: "https://docs.oracle.com/en/java/", category: "Programming", type: "html" },
  { name: "C++ Documentation", url: "https://en.cppreference.com/", category: "Programming", type: "html" },
  { name: "Vue.js Documentation", url: "https://vuejs.org/guide/", category: "Programming", type: "html" },
  { name: "Angular Documentation", url: "https://angular.io/docs", category: "Programming", type: "html" },
  { name: "Svelte Documentation", url: "https://svelte.dev/docs", category: "Programming", type: "html" },
  { name: "Next.js Documentation", url: "https://nextjs.org/docs", category: "Programming", type: "html" },
  { name: "Express.js Documentation", url: "https://expressjs.com/", category: "Programming", type: "html" },
  { name: "Django Documentation", url: "https://docs.djangoproject.com/", category: "Programming", type: "html" },
  { name: "Flask Documentation", url: "https://flask.palletsprojects.com/", category: "Programming", type: "html" },
  { name: "Spring Documentation", url: "https://spring.io/projects/spring-boot", category: "Programming", type: "html" },
  { name: "Laravel Documentation", url: "https://laravel.com/docs", category: "Programming", type: "html" },
  { name: "Ruby on Rails", url: "https://guides.rubyonrails.org/", category: "Programming", type: "html" },
  { name: "Swift Documentation", url: "https://docs.swift.org/swift-book/", category: "Programming", type: "html" },
  { name: "Kotlin Documentation", url: "https://kotlinlang.org/docs/", category: "Programming", type: "html" },
  { name: "Scala Documentation", url: "https://docs.scala-lang.org/", category: "Programming", type: "html" },
  { name: "PHP Documentation", url: "https://www.php.net/docs.php", category: "Programming", type: "html" },
  { name: "Laravel News", url: "https://laravel-news.com/", category: "Programming", type: "html" },
  { name: "React Native", url: "https://reactnative.dev/docs/getting-started", category: "Programming", type: "html" },
  { name: "Flutter Documentation", url: "https://docs.flutter.dev/", category: "Programming", type: "html" },
  { name: "Electron", url: "https://www.electronjs.org/docs", category: "Programming", type: "html" },
  { name: "Docker Documentation", url: "https://docs.docker.com/", category: "Programming", type: "html" },
  { name: "Kubernetes Documentation", url: "https://kubernetes.io/docs/", category: "Programming", type: "html" },
  { name: "Terraform Documentation", url: "https://www.terraform.io/docs", category: "Programming", type: "html" },
  { name: "AWS CDK", url: "https://docs.aws.amazon.com/cdk/", category: "Programming", type: "html" },
  { name: "GraphQL", url: "https://graphql.org/learn/", category: "Programming", type: "html" },
  { name: "Apollo GraphQL", url: "https://www.apollographql.com/docs/", category: "Programming", type: "html" },
  { name: "Prisma Documentation", url: "https://www.prisma.io/docs/", category: "Programming", type: "html" },
  { name: "TypeORM", url: "https://typeorm.io/", category: "Programming", type: "html" },
  { name: "Sequelize", url: "https://sequelize.org/", category: "Programming", type: "html" },
  { name: "Mongoose", url: "https://mongoosejs.com/docs/", category: "Programming", type: "html" },
  { name: "Redux Toolkit", url: "https://redux-toolkit.js.org/", category: "Programming", type: "html" },
  { name: "Zustand", url: "https://zustand-demo.pmnd.rs/", category: "Programming", type: "html" },
  { name: "Jotai", url: "https://jotai.org/", category: "Programming", type: "html" },
  { name: "Recoil", url: "https://recoiljs.org/", category: "Programming", type: "html" },
  { name: "Vite", url: "https://vitejs.dev/guide/", category: "Programming", type: "html" },
  { name: "Webpack", url: "https://webpack.js.org/concepts/", category: "Programming", type: "html" },
  { name: "Parcel", url: "https://parceljs.org/", category: "Programming", type: "html" },
  { name: "ESLint", url: "https://eslint.org/docs/", category: "Programming", type: "html" },
  { name: "Prettier", url: "https://prettier.io/docs/en/", category: "Programming", type: "html" },
  { name: "Jest", url: "https://jestjs.io/docs/getting-started", category: "Programming", type: "html" },
  { name: "Vitest", url: "https://vitest.dev/", category: "Programming", type: "html" },
  { name: "Playwright", url: "https://playwright.dev/", category: "Programming", type: "html" },
  { name: "Cypress", url: "https://docs.cypress.io/", category: "Programming", type: "html" },
  { name: "Testing Library", url: "https://testing-library.com/docs/", category: "Programming", type: "html" },
  { name: "Storybook", url: "https://storybook.js.org/docs/", category: "Programming", type: "html" },
  { name: "Tailwind CSS", url: "https://tailwindcss.com/docs/", category: "Programming", type: "html" },
  { name: "Bootstrap", url: "https://getbootstrap.com/", category: "Programming", type: "html" },
  { name: "Material UI", url: "https://mui.com/", category: "Programming", type: "html" },
  { name: "Chakra UI", url: "https://chakra-ui.com/", category: "Programming", type: "html" },
  { name: "Shadcn UI", url: "https://ui.shadcn.com/", category: "Programming", type: "html" },

  // ========== SCIENCE (40+) ==========
  { name: "NASA", url: "https://www.nasa.gov/", category: "Science", type: "html" },
  { name: "Scientific American", url: "https://www.scientificamerican.com/", category: "Science", type: "html" },
  { name: "Nature", url: "https://www.nature.com/", category: "Science", type: "html" },
  { name: "Science Daily", url: "https://www.sciencedaily.com/", category: "Science", type: "html" },
  { name: "Phys.org", url: "https://phys.org/", category: "Science", type: "html" },
  { name: "Live Science", url: "https://www.livescience.com/", category: "Science", type: "html" },
  { name: "New Scientist", url: "https://www.newscientist.com/", category: "Science", type: "html" },
  { name: "Khan Academy", url: "https://www.khanacademy.org/", category: "Science", type: "html" },
  { name: "Science News", url: "https://www.sciencenews.org/", category: "Science", type: "html" },
  { name: "Smithsonian", url: "https://www.smithsonianmag.com/", category: "Science", type: "html" },
  { name: "Discover Magazine", url: "https://www.discovermagazine.com/", category: "Science", type: "html" },
  { name: "Popular Science", url: "https://www.popsci.com/", category: "Science", type: "html" },
  { name: "Quanta Magazine", url: "https://quantamagazine.org/", category: "Science", type: "html" },
  { name: "Astronomy Magazine", url: "https://www.astronomy.com/", category: "Science", type: "html" },
  { name: "Physics Today", url: "https://physicstoday.scitation.org/", category: "Science", type: "html" },
  { name: "Chemistry World", url: "https://www.chemistryworld.com/", category: "Science", type: "html" },
  { name: "New Atlas", url: "https://newatlas.com/", category: "Science", type: "html" },
  { name: "IEEE Spectrum", url: "https://spectrum.ieee.org/", category: "Science", type: "html" },
  { name: "Science Focus", url: "https://www.sciencefocus.com/", category: "Science", type: "html" },
  { name: "HowStuffWorks", url: "https://www.howstuffworks.com/", category: "Science", type: "html" },
  { name: "Explain That Stuff", url: "https://www.explainthatstuff.com/", category: "Science", type: "html" },
  { name: "NOVA", url: "https://www.pbs.org/wgbh/nova/", category: "Science", type: "html" },
  { name: "National Geographic", url: "https://www.nationalgeographic.com/", category: "Science", type: "html" },
  { name: "Scientific American - Space", url: "https://www.scientificamerican.com/section/space/", category: "Science", type: "html" },
  { name: "Space.com", url: "https://www.space.com/", category: "Science", type: "html" },
  { name: "Universe Today", url: "https://www.universetoday.com/", category: "Science", type: "html" },
  { name: "Ars Technica - Science", url: "https://arstechnica.com/science/", category: "Science", type: "html" },
  { name: "Big Think", url: "https://bigthink.com/", category: "Science", type: "html" },
  { name: "ScienceDaily - Fossils", url: "https://www.sciencedaily.com/news/fossils_ruins/", category: "Science", type: "html" },
  { name: "ScienceDaily - Earth", url: "https://www.sciencedaily.com/news/earth_climate/", category: "Science", type: "html" },
  { name: "ScienceDaily - Biology", url: "https://www.sciencedaily.com/news/matter_energy/", category: "Science", type: "html" },
  { name: "ScienceDaily - Chemistry", url: "https://www.sciencedaily.com/news/matter_energy/chemistry/", category: "Science", type: "html" },
  { name: "PLOS ONE", url: "https://journals.plos.org/plosone/", category: "Science", type: "html" },
  { name: "eLife", url: "https://elifesciences.org/", category: "Science", type: "html" },
  { name: "PubMed", url: "https://pubmed.ncbi.nlm.nih.gov/", category: "Science", type: "html" },
  { name: "bioRxiv", url: "https://www.biorxiv.org/", category: "Science", type: "html" },
  { name: "arXiv", url: "https://arxiv.org/", category: "Science", type: "html" },
  { name: "ResearchGate", url: "https://www.researchgate.net/", category: "Science", type: "html" },
  { name: "Google Scholar", url: "https://scholar.google.com/", category: "Science", type: "html" },

  // ========== HEALTH (30+) ==========
  { name: "WebMD", url: "https://www.webmd.com/", category: "Health", type: "html" },
  { name: "Mayo Clinic", url: "https://www.mayoclinic.org/", category: "Health", type: "html" },
  { name: "Healthline", url: "https://www.healthline.com/", category: "Health", type: "html" },
  { name: "Medical News Today", url: "https://www.medicalnewstoday.com/", category: "Health", type: "html" },
  { name: "NIH", url: "https://www.nih.gov/", category: "Health", type: "html" },
  { name: "WHO", url: "https://www.who.int/", category: "Health", type: "html" },
  { name: "CDC", url: "https://www.cdc.gov/", category: "Health", type: "html" },
  { name: "Harvard Health", url: "https://www.health.harvard.edu/", category: "Health", type: "html" },
  { name: "Cleveland Clinic", url: "https://my.clevelandclinic.org/", category: "Health", type: "html" },
  { name: "Johns Hopkins", url: "https://www.hopkinsmedicine.org/", category: "Health", type: "html" },
  { name: "MedlinePlus", url: "https://medlineplus.gov/", category: "Health", type: "html" },
  { name: "FDA", url: "https://www.fda.gov/", category: "Health", type: "html" },
  { name: "WHO News", url: "https://www.who.int/news", category: "Health", type: "html" },
  { name: "Medical News Today - Nutrition", url: "https://www.medicalnewstoday.com/categories/nutrition", category: "Health", type: "html" },
  { name: "Medical News Today - Mental Health", url: "https://www.medicalnewstoday.com/categories/mental-health", category: "Health", type: "html" },
  { name: "Healthline - Nutrition", url: "https://www.healthline.com/nutrition", category: "Health", type: "html" },
  { name: "Healthline - Fitness", url: "https://www.healthline.com/nutrition/fitness", category: "Health", type: "html" },
  { name: "WebMD - Diet", url: "https://www.webmd.com/diet/default.htm", category: "Health", type: "html" },
  { name: "WebMD - Fitness", url: "https://www.webmd.com/fitness-exercise/default.htm", category: "Health", type: "html" },
  { name: "Nutrition.gov", url: "https://www.nutrition.gov/", category: "Health", type: "html" },
  { name: "Exercise is Medicine", url: "https://www.exerciseismedicine.org/", category: "Health", type: "html" },
  { name: "Mental Health America", url: "https://www.mhanational.org/", category: "Health", type: "html" },
  { name: "NIMH", url: "https://www.nimh.nih.gov/", category: "Health", type: "html" },
  { name: "PsyPost", url: "https://www.psypost.org/", category: "Health", type: "html" },
  { name: "Psychology Today", url: "https://www.psychologytoday.com/", category: "Health", type: "html" },
  { name: "APA", url: "https://www.apa.org/", category: "Health", type: "html" },
  { name: "Verywell Health", url: "https://www.verywellhealth.com/", category: "Health", type: "html" },
  { name: "Healthgrades", url: "https://www.healthgrades.com/", category: "Health", type: "html" },
  { name: "News Medical", url: "https://www.news-medical.net/", category: "Health", type: "html" },
  { name: "RxList", url: "https://www.rxlist.com/", category: "Health", type: "html" },

  // ========== BUSINESS & FINANCE (40+) ==========
  { name: "Bloomberg", url: "https://www.bloomberg.com/", category: "Business", type: "html" },
  { name: "Forbes", url: "https://www.forbes.com/", category: "Business", type: "html" },
  { name: "Business Insider", url: "https://www.businessinsider.com/", category: "Business", type: "html" },
  { name: "Investopedia", url: "https://www.investopedia.com/", category: "Finance", type: "html" },
  { name: "The Wall Street Journal", url: "https://www.wsj.com/", category: "Business", type: "html" },
  { name: "Financial Times", url: "https://www.ft.com/", category: "Business", type: "html" },
  { name: "Harvard Business Review", url: "https://hbr.org/", category: "Business", type: "html" },
  { name: "CNBC", url: "https://www.cnbc.com/", category: "Business", type: "html" },
  { name: "MarketWatch", url: "https://www.marketwatch.com/", category: "Finance", type: "html" },
  { name: "Yahoo Finance", url: "https://finance.yahoo.com/", category: "Finance", type: "html" },
  { name: "Seeking Alpha", url: "https://seekingalpha.com/", category: "Finance", type: "html" },
  { name: "The Economist", url: "https://www.economist.com/", category: "Business", type: "html" },
  { name: "Fortune", url: "https://fortune.com/", category: "Business", type: "html" },
  { name: "Inc.", url: "https://www.inc.com/", category: "Business", type: "html" },
  { name: "Fast Company", url: "https://www.fastcompany.com/", category: "Business", type: "html" },
  { name: "Entrepreneur", url: "https://www.entrepreneur.com/", category: "Business", type: "html" },
  { name: "Business News Daily", url: "https://www.businessnewsdaily.com/", category: "Business", type: "html" },
  { name: "Money", url: "https://money.com/", category: "Finance", type: "html" },
  { name: "Kiplinger", url: "https://www.kiplinger.com/", category: "Finance", type: "html" },
  { name: "The Balance", url: "https://www.thebalance.com/", category: "Finance", type: "html" },
  { name: "Investor's Business Daily", url: "https://www.investors.com/", category: "Finance", type: "html" },
  { name: "Barron's", url: "https://www.barrons.com/", category: "Finance", type: "html" },
  { name: "Morningstar", url: "https://www.morningstar.com/", category: "Finance", type: "html" },
  { name: "CoinDesk", url: "https://www.coindesk.com/", category: "Finance", type: "html" },
  { name: "CoinTelegraph", url: "https://cointelegraph.com/", category: "Finance", type: "html" },
  { name: "Nasdaq", url: "https://www.nasdaq.com/", category: "Finance", type: "html" },
  { name: "SEC", url: "https://www.sec.gov/", category: "Finance", type: "html" },
  { name: "Fidelity", url: "https://www.fidelity.com/", category: "Finance", type: "html" },
  { name: "Vanguard", url: "https://www.vanguard.com/", category: "Finance", type: "html" },
  { name: "Charles Schwab", url: "https://www.schwab.com/", category: "Finance", type: "html" },
  { name: "TD Ameritrade", url: "https://www.tdameritrade.com/", category: "Finance", type: "html" },
  { name: "E*TRADE", url: "https://www.etrade.com/", category: "Finance", type: "html" },
  { name: "Robinhood", url: "https://robinhood.com/", category: "Finance", type: "html" },
  { name: "PayPal", url: "https://www.paypal.com/", category: "Finance", type: "html" },
  { name: "Stripe", url: "https://stripe.com/", category: "Finance", type: "html" },
  { name: "Square", url: "https://squareup.com/", category: "Finance", type: "html" },
  { name: "Visa", url: "https://usa.visa.com/", category: "Finance", type: "html" },
  { name: "Mastercard", url: "https://www.mastercard.com/", category: "Finance", type: "html" },
  { name: "American Express", url: "https://www.americanexpress.com/", category: "Finance", type: "html" },

  // ========== NEWS (40+) ==========
  { name: "BBC News", url: "https://www.bbc.com/news", category: "News", type: "html" },
  { name: "Reuters", url: "https://www.reuters.com/", category: "News", type: "html" },
  { name: "NPR", url: "https://www.npr.org/", category: "News", type: "html" },
  { name: "The Guardian", url: "https://www.theguardian.com/", category: "News", type: "html" },
  { name: "Al Jazeera", url: "https://www.aljazeera.com/", category: "News", type: "html" },
  { name: "Associated Press", url: "https://apnews.com/", category: "News", type: "html" },
  { name: "CNN", url: "https://www.cnn.com/", category: "News", type: "html" },
  { name: "Fox News", url: "https://www.foxnews.com/", category: "News", type: "html" },
  { name: "NBC News", url: "https://www.nbcnews.com/", category: "News", type: "html" },
  { name: "ABC News", url: "https://abcnews.go.com/", category: "News", type: "html" },
  { name: "CBS News", url: "https://www.cbsnews.com/", category: "News", type: "html" },
  { name: "The New York Times", url: "https://www.nytimes.com/", category: "News", type: "html" },
  { name: "Washington Post", url: "https://www.washingtonpost.com/", category: "News", type: "html" },
  { name: "Los Angeles Times", url: "https://www.latimes.com/", category: "News", type: "html" },
  { name: "The Hill", url: "https://thehill.com/", category: "News", type: "html" },
  { name: "Politico", url: "https://www.politico.com/", category: "News", type: "html" },
  { name: "Vox", url: "https://www.vox.com/", category: "News", type: "html" },
  { name: "HuffPost", url: "https://www.huffpost.com/", category: "News", type: "html" },
  { name: "USA Today", url: "https://www.usatoday.com/", category: "News", type: "html" },
  { name: "NPR News", url: "https://www.npr.org/sections/news/", category: "News", type: "html" },
  { name: "BBC World", url: "https://www.bbc.com/news/world", category: "News", type: "html" },
  { name: "Euronews", url: "https://www.euronews.com/", category: "News", type: "html" },
  { name: "France24", url: "https://www.france24.com/", category: "News", type: "html" },
  { name: "DW", url: "https://www.dw.com/", category: "News", type: "html" },
  { name: "The Independent", url: "https://www.independent.co.uk/", category: "News", type: "html" },
  { name: "The Telegraph", url: "https://www.telegraph.co.uk/", category: "News", type: "html" },
  { name: "The Sun", url: "https://www.thesun.co.uk/", category: "News", type: "html" },
  { name: "Daily Mail", url: "https://www.dailymail.co.uk/", category: "News", type: "html" },
  { name: "Sky News", url: "https://news.sky.com/", category: "News", type: "html" },
  { name: "ABC News Australia", url: "https://www.abc.net.au/news", category: "News", type: "html" },
  { name: "CBC News", url: "https://www.cbc.ca/news", category: "News", type: "html" },
  { name: "CCTV", url: "https://www.cctv.com/", category: "News", type: "html" },
  { name: "RT", url: "https://www.rt.com/", category: "News", type: "html" },
  { name: "Times of India", url: "https://timesofindia.indiatimes.com/", category: "News", type: "html" },
  { name: "The Japan Times", url: "https://www.japantimes.co.jp/", category: "News", type: "html" },
  { name: "China Daily", url: "https://www.chinadaily.com.cn/", category: "News", type: "html" },
  { name: "Haaretz", url: "https://www.haaretz.com/", category: "News", type: "html" },
  { name: "The National", url: "https://www.thenationalnews.com/", category: "News", type: "html" },

  // ========== EDUCATION (30+) ==========
  { name: "Coursera", url: "https://www.coursera.org/", category: "Education", type: "html" },
  { name: "edX", url: "https://www.edx.org/", category: "Education", type: "html" },
  { name: "TED Talks", url: "https://www.ted.com/", category: "Education", type: "html" },
  { name: "Wikipedia", url: "https://en.wikipedia.org/wiki/Main_Page", category: "Education", type: "html" },
  { name: "Britannica", url: "https://www.britannica.com/", category: "Education", type: "html" },
  { name: "Khan Academy", url: "https://www.khanacademy.org/", category: "Education", type: "html" },
  { name: "Udemy", url: "https://www.udemy.com/", category: "Education", type: "html" },
  { name: "Skillshare", url: "https://www.skillshare.com/", category: "Education", type: "html" },
  { name: "Pluralsight", url: "https://www.pluralsight.com/", category: "Education", type: "html" },
  { name: "LinkedIn Learning", url: "https://www.linkedin.com/learning/", category: "Education", type: "html" },
  { name: "Codecademy", url: "https://www.codecademy.com/", category: "Education", type: "html" },
  { name: "Datacamp", url: "https://www.datacamp.com/", category: "Education", type: "html" },
  { name: "Udacity", url: "https://www.udacity.com/", category: "Education", type: "html" },
  { name: "MasterClass", url: "https://www.masterclass.com/", category: "Education", type: "html" },
  { name: "Greatist", url: "https://greatist.com/", category: "Education", type: "html" },
  { name: "OpenLearn", url: "https://www.open.edu/openlearn/", category: "Education", type: "html" },
  { name: "MIT OpenCourseWare", url: "https://ocw.mit.edu/", category: "Education", type: "html" },
  { name: "Stanford Online", url: "https://online.stanford.edu/", category: "Education", type: "html" },
  { name: "Harvard Online", url: "https://online.harpvard.edu/", category: "Education", type: "html" },
  { name: "Yale Online", url: "https://online.yale.edu/", category: "Education", type: "html" },
  { name: "OpenStax", url: "https://openstax.org/", category: "Education", type: "html" },
  { name: "Saylor Academy", url: "https://www.saylor.org/", category: "Education", type: "html" },
  { name: "FutureLearn", url: "https://www.futurelearn.com/", category: "Education", type: "html" },
  { name: "iversity", url: "https://iversity.org/", category: "Education", type: "html" },
  { name: "OpenCulture", url: "https://www.openculture.com/", category: "Education", type: "html" },
  { name: "Big Think", url: "https://bigthink.com/", category: "Education", type: "html" },
  { name: "TED-Ed", url: "https://ed.ted.com/", category: "Education", type: "html" },
  { name: "Crash Course", url: "https://www.youtube.com/user/crashcourse", category: "Education", type: "html" },
  { name: "Numberphile", url: "https://www.numberphile.com/", category: "Education", type: "html" },
  { name: "3Blue1Brown", url: "https://www.3blue1brown.com/", category: "Education", type: "html" },
  { name: "Veritasium", url: "https://www.veritasium.com/", category: "Education", type: "html" },
  { name: "SmarterEveryDay", url: "https://www.smartereveryday.com/", category: "Education", type: "html" },

  // ========== ENTERTAINMENT (30+) ==========
  { name: "IMDb", url: "https://www.imdb.com/", category: "Entertainment", type: "html" },
  { name: "Rotten Tomatoes", url: "https://www.rottentomatoes.com/", category: "Entertainment", type: "html" },
  { name: "IGN", url: "https://www.ign.com/", category: "Entertainment", type: "html" },
  { name: "Variety", url: "https://variety.com/", category: "Entertainment", type: "html" },
  { name: "Pitchfork", url: "https://pitchfork.com/", category: "Entertainment", type: "html" },
  { name: "Rolling Stone", url: "https://www.rollingstone.com/", category: "Entertainment", type: "html" },
  { name: "Billboard", url: "https://www.billboard.com/", category: "Entertainment", type: "html" },
  { name: "Metacritic", url: "https://www.metacritic.com/", category: "Entertainment", type: "html" },
  { name: "Box Office Mojo", url: "https://www.boxofficemojo.com/", category: "Entertainment", type: "html" },
  { name: "TV Guide", url: "https://www.tvguide.com/", category: "Entertainment", type: "html" },
  { name: "TV Tropes", url: "https://tvtropes.org/", category: "Entertainment", type: "html" },
  { name: "Screen Rant", url: "https://screenrant.com/", category: "Entertainment", type: "html" },
  { name: "Collider", url: "https://collider.com/", category: "Entertainment", type: "html" },
  { name: "Den of Geek", url: "https://www.denofgeek.com/", category: "Entertainment", type: "html" },
  { name: "Film Threat", url: "https://filmthreat.com/", category: "Entertainment", type: "html" },
  { name: "PopCrush", url: "https://popcrush.com/", category: "Entertainment", type: "html" },
  { name: "NME", url: "https://www.nme.com/", category: "Entertainment", type: "html" },
  { name: "Kotaku", url: "https://kotaku.com/", category: "Entertainment", type: "html" },
  { name: "Polygon", url: "https://www.polygon.com/", category: "Entertainment", type: "html" },
  { name: "Eurogamer", url: "https://www.eurogamer.com/", category: "Entertainment", type: "html" },
  { name: "GamesRadar", url: "https://www.gamesradar.com/", category: "Entertainment", type: "html" },
  { name: "PC Gamer", url: "https://www.pcgamer.com/", category: "Entertainment", type: "html" },
  { name: "GameSpot", url: "https://www.gamespot.com/", category: "Entertainment", type: "html" },
  { name: "Game Informer", url: "https://www.gameinformer.com/", category: "Entertainment", type: "html" },
  { name: "Rock Paper Shotgun", url: "https://www.rockpapershotgun.com/", category: "Entertainment", type: "html" },
  { name: "Kinda Funny", url: "https://www.kindafunny.com/", category: "Entertainment", type: "html" },
  { name: "AV Club", url: "https://www.avclub.com/", category: "Entertainment", type: "html" },
  { name: "Vulture", url: "https://www.vulture.com/", category: "Entertainment", type: "html" },
  { name: "EW", url: "https://ew.com/", category: "Entertainment", type: "html" },
  { name: "People", url: "https://people.com/", category: "Entertainment", type: "html" },

  // ========== GOVERNMENT (20+) ==========
  { name: "White House", url: "https://www.whitehouse.gov/", category: "Government", type: "html" },
  { name: "Supreme Court", url: "https://www.supremecourt.gov/", category: "Government", type: "html" },
  { name: "US Census Bureau", url: "https://www.census.gov/", category: "Government", type: "html" },
  { name: "World Bank", url: "https://www.worldbank.org/", category: "Government", type: "html" },
  { name: "United Nations", url: "https://www.un.org/", category: "Government", type: "html" },
  { name: "CIA", url: "https://www.cia.gov/", category: "Government", type: "html" },
  { name: "FBI", url: "https://www.fbi.gov/", category: "Government", type: "html" },
  { name: "NASA", url: "https://www.nasa.gov/", category: "Government", type: "html" },
  { name: "National Archives", url: "https://www.archives.gov/", category: "Government", type: "html" },
  { name: "Library of Congress", url: "https://www.loc.gov/", category: "Government", type: "html" },
  { name: "US Senate", url: "https://www.senate.gov/", category: "Government", type: "html" },
  { name: "US House of Representatives", url: "https://www.house.gov/", category: "Government", type: "html" },
  { name: "IRS", url: "https://www.irs.gov/", category: "Government", type: "html" },
  { name: "Social Security", url: "https://www.ssa.gov/", category: "Government", type: "html" },
  { name: "Department of Education", url: "https://www.ed.gov/", category: "Government", type: "html" },
  { name: "Department of Health", url: "https://www.hhs.gov/", category: "Government", type: "html" },
  { name: "Department of Energy", url: "https://www.energy.gov/", category: "Government", type: "html" },
  { name: "Department of Defense", url: "https://www.defense.gov/", category: "Government", type: "html" },
  { name: "NASA JPL", url: "https://www.jpl.nasa.gov/", category: "Government", type: "html" },
  { name: "US Patent Office", url: "https://www.uspto.gov/", category: "Government", type: "html" },

  // ========== SPORTS (25+) ==========
  { name: "ESPN", url: "https://www.espn.com/", category: "Sports", type: "html" },
  { name: "BBC Sport", url: "https://www.bbc.com/sport", category: "Sports", type: "html" },
  { name: "Sports Illustrated", url: "https://www.si.com/", category: "Sports", type: "html" },
  { name: "The Athletic", url: "https://theathletic.com/", category: "Sports", type: "html" },
  { name: "Yahoo Sports", url: "https://sports.yahoo.com/", category: "Sports", type: "html" },
  { name: "CBS Sports", url: "https://www.cbssports.com/", category: "Sports", type: "html" },
  { name: "NBC Sports", url: "https://www.nbcsports.com/", category: "Sports", type: "html" },
  { name: "Fox Sports", url: "https://www.foxsports.com/", category: "Sports", type: "html" },
  { name: "Bleacher Report", url: "https://bleacherreport.com/", category: "Sports", type: "html" },
  { name: "Sky Sports", url: "https://www.skysports.com/", category: "Sports", type: "html" },
  { name: "Goal", url: "https://www.goal.com/", category: "Sports", type: "html" },
  { name: "Transfermarkt", url: "https://www.transfermarkt.com/", category: "Sports", type: "html" },
  { name: "NBA", url: "https://www.nba.com/", category: "Sports", type: "html" },
  { name: "NFL", url: "https://www.nfl.com/", category: "Sports", type: "html" },
  { name: "MLB", url: "https://www.mlb.com/", category: "Sports", type: "html" },
  { name: "NHL", url: "https://www.nhl.com/", category: "Sports", type: "html" },
  { name: "PGA Tour", url: "https://www.pgatour.com/", category: "Sports", type: "html" },
  { name: "UFC", url: "https://www.ufc.com/", category: "Sports", type: "html" },
  { name: "WWE", url: "https://www.wwe.com/", category: "Sports", type: "html" },
  { name: "Tennis", url: "https://www.atptour.com/", category: "Sports", type: "html" },
  { name: "Olympics", url: "https://olympics.com/", category: "Sports", type: "html" },
  { name: "FIFA", url: "https://www.fifa.com/", category: "Sports", type: "html" },
  { name: "Cricket", url: "https://www.icc-cricket.com/", category: "Sports", type: "html" },
  { name: "Rugby", url: "https://www.worldrugby.org/", category: "Sports", type: "html" },
  { name: "NCAA", url: "https://www.ncaa.com/", category: "Sports", type: "html" },

  // ========== LIFESTYLE (25+) ==========
  { name: "Lifehacker", url: "https://lifehacker.com/", category: "Lifestyle", type: "html" },
  { name: "The Spruce", url: "https://www.thespruce.com/", category: "Lifestyle", type: "html" },
  { name: "Wikihow", url: "https://www.wikihow.com/", category: "Lifestyle", type: "html" },
  { name: "The Knot", url: "https://www.theknot.com/", category: "Lifestyle", type: "html" },
  { name: "Zillow", url: "https://www.zillow.com/", category: "Lifestyle", type: "html" },
  { name: "Realtor", url: "https://www.realtor.com/", category: "Lifestyle", type: "html" },
  { name: "TripAdvisor", url: "https://www.tripadvisor.com/", category: "Lifestyle", type: "html" },
  { name: "Yelp", url: "https://www.yelp.com/", category: "Lifestyle", type: "html" },
  { name: "Pinterest", url: "https://www.pinterest.com/", category: "Lifestyle", type: "html" },
  { name: "Allrecipes", url: "https://www.allrecipes.com/", category: "Lifestyle", type: "html" },
  { name: "Food Network", url: "https://www.foodnetwork.com/", category: "Lifestyle", type: "html" },
  { name: "Bon Appetit", url: "https://www.bonappetit.com/", category: "Lifestyle", type: "html" },
  { name: "Serious Eats", url: "https://www.seriouseats.com/", category: "Lifestyle", type: "html" },
  { name: "Eating Well", url: "https://www.eatingwell.com/", category: "Lifestyle", type: "html" },
  { name: "Cook's Illustrated", url: "https://www.cooksillustrated.com/", category: "Lifestyle", type: "html" },
  { name: "The Pioneer Woman", url: "https://www.thepioneerwoman.com/", category: "Lifestyle", type: "html" },
  { name: "Simply Recipes", url: "https://www.simplyrecipes.com/", category: "Lifestyle", type: "html" },
  { name: "BuzzFeed Tasty", url: "https://www.buzzfeed.com/aharoni/tasty-cooking-videos", category: "Lifestyle", type: "html" },
  { name: "Better Homes & Gardens", url: "https://www.bhg.com/", category: "Lifestyle", type: "html" },
  { name: "HGTV", url: "https://www.hgtv.com/", category: "Lifestyle", type: "html" },
  { name: "Apartment Therapy", url: "https://www.apartmenttherapy.com/", category: "Lifestyle", type: "html" },
  { name: "Remodelista", url: "https://www.remodelista.com/", category: "Lifestyle", type: "html" },
  { name: "Gardenista", url: "https://www.gardenista.com/", category: "Lifestyle", type: "html" },
  { name: "MindBodyGreen", url: "https://www.mindbodygreen.com/", category: "Lifestyle", type: "html" },
  { name: "Well+Good", url: "https://www.wellandgood.com/", category: "Lifestyle", type: "html" },

  // ========== OPEN DATA (20+) ==========
  { name: "Data.gov", url: "https://www.data.gov/", category: "Open Data", type: "html" },
  { name: "Kaggle", url: "https://www.kaggle.com/", category: "Open Data", type: "html" },
  { name: "GitHub", url: "https://github.com/", category: "Open Data", type: "html" },
  { name: "Stack Exchange", url: "https://stackexchange.com/", category: "Open Data", type: "html" },
  { name: "Reddit", url: "https://www.reddit.com/", category: "Open Data", type: "html" },
  { name: "Archive.org", url: "https://archive.org/", category: "Open Data", type: "html" },
  { name: "OpenStreetMap", url: "https://www.openstreetmap.org/", category: "Open Data", type: "html" },
  { name: "Wikidata", url: "https://www.wikidata.org/", category: "Open Data", type: "html" },
  { name: "Wikimedia Commons", url: "https://commons.wikimedia.org/", category: "Open Data", type: "html" },
  { name: "Data.world", url: "https://data.world/", category: "Open Data", type: "html" },
  { name: "World Bank Data", url: "https://data.worldbank.org/", category: "Open Data", type: "html" },
  { name: "UN Data", url: "https://data.un.org/", category: "Open Data", type: "html" },
  { name: "OECD Data", url: "https://data.oecd.org/", category: "Open Data", type: "html" },
  { name: "Google Dataset Search", url: "https://datasetsearch.research.google.com/", category: "Open Data", type: "html" },
  { name: "EU Open Data", url: "https://data.europa.eu/", category: "Open Data", type: "html" },
  { name: "UK Data Service", url: "https://ukdataservice.ac.uk/", category: "Open Data", type: "html" },
  { name: "FiveThirtyEight", url: "https://data.fivethirtyeight.com/", category: "Open Data", type: "html" },
  { name: "NASA Data", url: "https://data.nasa.gov/", category: "Open Data", type: "html" },
  { name: "NOAA Data", url: "https://data.noaa.gov/", category: "Open Data", type: "html" },
  { name: "NIH Data", url: "https://data.nlm.nih.gov/", category: "Open Data", type: "html" },
];

export const RSS_FEEDS = [
  { name: "Hacker News RSS", url: "https://news.ycombinator.com/rss", category: "Technology" },
  { name: "TechCrunch RSS", url: "https://techcrunch.com/feed/", category: "Technology" },
  { name: "The Verge RSS", url: "https://www.theverge.com/rss/index.xml", category: "Technology" },
  { name: "Wired RSS", url: "https://www.wired.com/feed/rss", category: "Technology" },
  { name: "BBC News RSS", url: "http://feeds.bbci.co.uk/news/rss.xml", category: "News" },
  { name: "Reuters RSS", url: "https://www.reutersagency.com/feed/", category: "News" },
  { name: "NASA RSS", url: "https://www.nasa.gov/rss/dyn/breaking_news.rss", category: "Science" },
  { name: "NYTimes Tech RSS", url: "https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml", category: "Technology" }
];

export function getSourcesByCategory(category: string): DataSource[] {
  return DATA_SOURCES.filter(s => s.category === category);
}

export function getAllCategories(): string[] {
  return [...new Set(DATA_SOURCES.map(s => s.category))];
}
